require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LocalesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Locale. As you add validations to Locale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LocalesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all locales as @locales" do
      locale = Locale.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:locales)).to eq([locale])
    end
  end

  describe "GET #show" do
    it "assigns the requested locale as @locale" do
      locale = Locale.create! valid_attributes
      get :show, {:id => locale.to_param}, valid_session
      expect(assigns(:locale)).to eq(locale)
    end
  end

  describe "GET #new" do
    it "assigns a new locale as @locale" do
      get :new, {}, valid_session
      expect(assigns(:locale)).to be_a_new(Locale)
    end
  end

  describe "GET #edit" do
    it "assigns the requested locale as @locale" do
      locale = Locale.create! valid_attributes
      get :edit, {:id => locale.to_param}, valid_session
      expect(assigns(:locale)).to eq(locale)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Locale" do
        expect {
          post :create, {:locale => valid_attributes}, valid_session
        }.to change(Locale, :count).by(1)
      end

      it "assigns a newly created locale as @locale" do
        post :create, {:locale => valid_attributes}, valid_session
        expect(assigns(:locale)).to be_a(Locale)
        expect(assigns(:locale)).to be_persisted
      end

      it "redirects to the created locale" do
        post :create, {:locale => valid_attributes}, valid_session
        expect(response).to redirect_to(Locale.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved locale as @locale" do
        post :create, {:locale => invalid_attributes}, valid_session
        expect(assigns(:locale)).to be_a_new(Locale)
      end

      it "re-renders the 'new' template" do
        post :create, {:locale => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested locale" do
        locale = Locale.create! valid_attributes
        put :update, {:id => locale.to_param, :locale => new_attributes}, valid_session
        locale.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested locale as @locale" do
        locale = Locale.create! valid_attributes
        put :update, {:id => locale.to_param, :locale => valid_attributes}, valid_session
        expect(assigns(:locale)).to eq(locale)
      end

      it "redirects to the locale" do
        locale = Locale.create! valid_attributes
        put :update, {:id => locale.to_param, :locale => valid_attributes}, valid_session
        expect(response).to redirect_to(locale)
      end
    end

    context "with invalid params" do
      it "assigns the locale as @locale" do
        locale = Locale.create! valid_attributes
        put :update, {:id => locale.to_param, :locale => invalid_attributes}, valid_session
        expect(assigns(:locale)).to eq(locale)
      end

      it "re-renders the 'edit' template" do
        locale = Locale.create! valid_attributes
        put :update, {:id => locale.to_param, :locale => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested locale" do
      locale = Locale.create! valid_attributes
      expect {
        delete :destroy, {:id => locale.to_param}, valid_session
      }.to change(Locale, :count).by(-1)
    end

    it "redirects to the locales list" do
      locale = Locale.create! valid_attributes
      delete :destroy, {:id => locale.to_param}, valid_session
      expect(response).to redirect_to(locales_url)
    end
  end

end
